[tool.poetry]
name = "PDaltagent"
version = "0.1.0"
description = ""
authors = ["Martin Stone <martin@pagerduty.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23"
celery = {extras = ["redis"], version = "^4.4"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
pdagentd = 'pdaltagent.tasks:consume'
pdpollerd = 'pdaltagent.tasks:poll'
pd-send = 'pdaltagent.pdsend:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
